'use client'

import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import Navbar from '/components/Navbar'
import Footer from '/components/Footer'
import Head from 'next/head'
import ThemeToggle from '@/public/js/ThemeToggle'
import ColorTheme from '@/public/js/ColorTheme'




const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Slideshub',
  description: 'Generated by create next app',
  charset:"utf-8",
  type: 'website',
  url: 'https://slideshub.netlify.app',
  site_name: 'Slideshub',
  author: 'Slideshub',
  // twitter_username: '@slideshub',
  image: '/images/icon.png',
  favicon: '/images/favicon.png',
  og:{
    title: 'Slideshub',
    type: 'website',
    url: 'https://slideshub.netlify.app/',
    description: 'Generated by create next app',
    image: '/public/thumbnail.png',

  }

}

export default function RootLayout({ children }) {

  return (
<>
    <Head>
    <meta name="viewport" content="width=device-width, initial-scale=1"
         />
    
  
         <ColorTheme/>
   
    </Head>
  


      <body className={inter.className}>
      <Navbar/>
      {children}
  
      <ThemeToggle/>
      <Footer/>
      </body>
      </>
  )
}
